; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32s3]
platform = espressif32
; Using ESP32-S3 board with native USB support
; Ensure pin mappings below match your hardware wiring for this board.
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L
lib_deps =
	adafruit/Adafruit GC9A01A @ ^1.1.0
	adafruit/Adafruit GFX Library @ ^1.12.3
	bblanchon/ArduinoJson @ ^7.4.2

build_flags =
	-DTFT_SCK_PIN=12
	-DTFT_MOSI_PIN=11
	-DTFT_MISO_PIN=13
	-DTFT_CS_PIN=10
	-DTFT_DC_PIN=39
	-DTFT_RST_PIN=40
	-DTFT_BL_PIN=7
	-DMENU_BUTTON_PIN=18
	-DBUTTON_PRIMARY_PIN=14
	-DTOUCH_SDA_PIN=8
	-DTOUCH_SCL_PIN=9
	-DTOUCH_I2C_ADDR=0x15
	-DTOUCH_INT_PIN=41
	-DTOUCH_RST_PIN=       ;Not connected
	-DTOUCH_CALIB_X_OFFSET=0
	-DTOUCH_CALIB_Y_OFFSET=0
	-DTOUCH_CALIB_X_SCALE=1.0f
	-DTOUCH_CALIB_Y_SCALE=1.0f
	-DDEBOUNCE_TIME_MS=50
	-DLONG_PRESS_TIME_MS=1000